### ISSUE TITLE
[BUG] Client OpenAPI specifications (on dev) contain structural errors

### ISSUE THREAD

**Issue by Spiess** [vitrivr/vitrivr-engine#126]
# Description
The official Swagger OpenAPI editor (used to convert from json to yaml OAS) labels the following structural errors in the client OAS generated from current dev branch:
```
Structural error at paths./api/{schema}/fetch/{exporter}/{retrievableId}.get.parameters.0.required
should be equal to one of the allowed values allowedValues: true
Jump to line 50
Structural error at paths./api/{schema}/fetch/{exporter}/{retrievableId}.get.parameters.1.required
should be equal to one of the allowed values allowedValues: true
Jump to line 60
Structural error at paths./api/{schema}/fetch/{exporter}/{retrievableId}.get.parameters.2.required
should be equal to one of the allowed values allowedValues: true
Jump to line 70
```

## Steps To Reproduce
1. Run the dev vitrivr-engine server.
2. Download the json OAS.
3. Open the OAS on https://editor.swagger.io.

OAS attached: [openapi.json](https://github.com/user-attachments/files/18062833/openapi.json)

**Comment by ppanopticon** [comment]
I have just committed a fix for this on `dev`. Can you confirm, that this solves your issue?

**Comment by Spiess** [comment]
I can confirm this has solved my issue and fixed OpenAPI client code generation.
