### ISSUE TITLE
Prepare for New Plugins

### ISSUE THREAD

**Issue by faberf** [vitrivr/vitrivr-engine#17]
We are preparing to develop new plugins and need to ensure our Maven dependencies are properly organized and other necessary steps (?) are taken in order to facilitate this.

- [x] Sort Dependencies
- [ ] Prepare Example Plugin

**Comment by ppanopticon** [comment]
In the meanwhile, several modules (former plugins) have been created and `vitrivr-engine` is being used within the XReco project. I see two ToDo's (please comment):

- [ ] Update documentation on how to create plugins
- [ ] Create an example project

Do you see any other things that ought to be addressed @lucaro @sauterl @net-cscience-raphael ?

**Comment by lucaro** [comment]
No, I think having the Maven dependencies structured such that this can easily be done is the most important for now.

**Comment by ppanopticon** [comment]
Closing issue since this has been done. Adding task for documentation to respective issue.
