### ISSUE TITLE
Refactor the error handling in vitrivr-engine.

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#21]
For productive operation, vitrivr-engine must be equipped with minimum error handling. Error handling must allow meaningful logging, and errors must be thrown in the event of faulty processes and not caught blindly.

**Comment by ppanopticon** [comment]
What is the status on this issue? What steps have been taken so for? And what are the design goals?

One aspect not to miss is that of data consistency. At the moment, if anything happens during extraction, the stored data is very likely to end-up all-over-the-place.

**Comment by net-cscience-raphael** [comment]
Close due to a8604aee5fb55c8d76fd1e4ad28525ed9b3abf3a and #22
