### ISSUE TITLE
External Feature Extraction Server

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#30]
Completion of the feature extraction server and its integration into `vitrivr-engine` including provision of the minimum features required in the issue. The features are tested for functionality.

**Comment by ppanopticon** [comment]
What is the status on this?

**Comment by faberf** [comment]
The functionality is implemented. The tests and running the server on a node are planned for this week.

**Comment by ppanopticon** [comment]
Done! Open issues for specific problems or bugs.
