### ISSUE TITLE
Minimal documentation

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#31]
Minimal documentation must be prepared. This includes:
- [x] Basic setup
- [x] Using vitrivr-engine as dependency
- [x] Creating vitrivr-engine plugins
- [x] Configuration Extraction Pipeline including a minimal example.
- [x] Configuration Query Pipeline  including  minimal examples (NNS, Boolean, etc.)
- [x] List of existing operators including a brief description
- [x]  List of existing descriptors / features including a brief description
- [x] Example

**Comment by sauterl** [comment]
The wiki has been set-up. There is a small part regarding query pipelines still missing (e.g. a real-world example), which will be added soon. 

Ideally, now that the documentation is here in the wiki, there should be an explicit effort to keep it up-to-date.

My part is done here, hence I remove myself from the list of assignees.
