### ISSUE TITLE
Add and Test Whisper ASR feature.

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#36]

**Comment by lucaro** [comment]
What we did on the cineast side of things is to have a method for decoding standard subtitle formats. This has the benefit that it does not matter where the subtitles come from. I would suggest doing something similar here. Subtitle generation using whisper or any other mechanism can then be a pre-processing step. Possibly we might want to have a pipeline that also takes care of such pre-processing, but that sounds more like a later addition.

**Comment by ppanopticon** [comment]
What's the status on this? Is there a deadline for this issue?

**To add my five cents here:** While having an import functionality for subtitles certainly sounds like a nice idea, I ask myself if having a fully integrated Whisper ASR `Analyser` wouldn't be worthwhile anyway?

**Comment by ppanopticon** [comment]
I'd like to discuss the status of this during our meeting on Friday.

**Comment by ppanopticon** [comment]
Done! Closed based on feedback from weekly meeting.
