### ISSUE TITLE
Migration of MLClip

### ISSUE THREAD

**Issue by rahelarnold98** [vitrivr/vitrivr-engine#44]
The MLClip feature might already be extracted in Cineast format. Therefore, a migration for vitrivr-engine is required.

**Comment by sauterl** [comment]
Might save time in #42

**Comment by faberf** [comment]
I assume this simple involves a migration of the data, not the code?

**Comment by sauterl** [comment]
Yes, this involves migrating the existing data (on p10: `/tank/Datasets/lsc23/*.zip` ) from the cineast-cottontail schema to the vitrivr-engine compatible cottontail schema

**Comment by sauterl** [comment]
After some off-line discussion we decided that @faberf concentrates on the python extraction server and we do not re-use feature vectors from the past.
