### ISSUE TITLE
Move OCRSearch from Cineast to vitrivr-engine

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#5]
# Task Description
Cineast sported OCR search, which must be migrated to vitrivr-engine. The search functionality relies on labels provided with the V3C collection. Hence, no extraction is needed (for now).

- [x] **Re-implement OCR search:** Create an ``Analyser`` and ``Retriever`` implementation that allows for OCR search. 

## Dependencies
- Issue #6 must be tackled (in parts) so that the OCR features existing in Cineast can be transferred.

## Boundary Conditions
- The implementation can be based on what is done in Cineast's `OCRSearch` feature.
- Extraction not needed at this point.

**Comment by lucaro** [comment]
What is the status here? Given that we would want to use this for VBS, it should be available as soon as possible...
