### ISSUE TITLE
Memory leak during ingest

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#54]
During the ingest setup with the attached pipeline configuration, we run into a memory leak in approx 5min @ 14GB.

```json
{
  "schema": "PTT",
  "context": {
    "contentFactory": "InMemoryContentFactory",
    "resolverFactory": "DiskResolver",
    "parameters": {
      "location": "D:/ptt/thumbnails/"
    }
  },
  "enumerator": {
    "type": "ENUMERATOR",
    "factory": "FileSystemEnumerator",
    "parameters": {
      "path": "D:/ptt/PTT-Testdaten",
      "mediaTypes": "IMAGE;VIDEO",
      "depth": "5"
    }
  },
  "decoder": {
    "factory": "ImageDecoder"
  },
  "operators": {
    "pass": {
      "type": "SEGMENTER",
      "factory": "PassThroughSegmenter"
    },
    "allContent": {
      "type": "AGGREGATOR",
      "factory": "AllContentAggregator"
    },
    "avgColor": {
      "type": "EXTRACTOR",
      "fieldName": "averagecolor"
    },
    "thumbs": {
      "type": "EXPORTER",
      "exporterName": "thumbnail",
      "parameters": {
        "maxSideResolution": "350",
        "mimeType": "JPG"
      }
    },
    "fileMeta": {
      "type": "EXTRACTOR",
      "fieldName": "file"
    }
  },
  "operations": {
    "stage1": {"operator": "pass"},
    "stage2": {"operator": "allContent"},
    "stage3": {"operator": "avgColor"},
    "stage4": {"operator": "thumbs"},
    "stage5": {"operator": "fileMeta"}
  }
}
```

![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/34ef9d0c-2472-4a87-933d-17b8b9ef20e2)

![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/fbbcabb9-6225-496d-a513-24dc5e453a0b)

@10s

![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/514abbf7-48e4-44e0-8d7a-58c8adb26478)

@240s
![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/28c7adb7-382d-49e2-be3a-7bacd079b33f)

![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/76fa51b0-6348-458a-b0d4-d78efbd6b21f)
![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/ad311d05-1e9b-40a9-aa63-e3d81c0dcb46)

**Comment by lucaro** [comment]
Looks like a component doesn't block properly to exert the necessary backpressure on the flow. This used to work, apparently, some changes broke it, that buffer size should not be 64, as shown in your last screenshot. A short-term fix would be to not use the `"InMemoryContentFactory"`.

**Comment by sauterl** [comment]
I guess this issue can be closed due to the introduction of the `CachedContentFactory` ?

**Comment by net-cscience-raphael** [comment]
'CachedContentFactory' solves the proplem for now.
