### ISSUE TITLE
Handling of data URLs within ExternalWithFloatVectorDescriptorAnalyser

### ISSUE THREAD

**Issue by rahelarnold98** [vitrivr/vitrivr-engine#56]
While refactoring, the following about data URLs within the [ExternalWithFloatVectorDescriptorAnalyser](https://github.com/vitrivr/vitrivr-engine/blob/main/vitrivr-engine-plugin-features/src/main/kotlin/org/vitrivr/engine/base/features/external/common/ExternalWithFloatVectorDescriptorAnalyser.kt) were noticed: Currently, the code involves encoding a data URL within another data URL, which seems unconventional and potentially problematic.

Current Implementation:

`val requestBody = URLEncoder.encode("data:text/plain;charset=utf-8,$base64", StandardCharsets.UTF_8.toString())`

It seems more appropriate to directly send a regular data URL for different content types instead of encapsulating it within another URL. This would necessitate adjustments on the server side to accommodate this change.

Action Items:

- [x] Review the current implementation within ExternalWithFloatVectorDescriptorAnalyser.
- [x] Review the current implementation within the server.

**Comment by ppanopticon** [comment]
What is the update on this issue?

**Comment by rahelarnold98** [comment]
Over time, this issue was already solved by reorganizing and removing ExternalWithFloatVectorDescriptorAnalyser.kt.
We are currently encoding the content to be sent into a Base64-encoded string and formatting it as a data URL. Afterwards, we use URLEncoder.encode() to safely include the data URL in a URL query parameter.

If there is no vote against it, in my opinion, we can close this issue.  @ppanopticon Do you agree?
