### ISSUE TITLE
Write existing metadata as EXIF

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-engine#61]
To use #60 and #59 , we require that the existing metadata is written in an industry standard such that it is readable by the extractor of #60 again.

Open discussion: how to handle spatio-temporal data which is sparse in the provided metadata, for which I see two options:

"Option 1*: Keep sparsity and write metadata 1:1 as in provided

*Option 2*: Artificially add metadata based on previous entries as sensors wrote spatio-temporal information with a lower cadence

**Comment by sauterl** [comment]
This is an LSC related issue which is required in order to test #60 which is not to be implemented as part of vitrivr-engine. However, since we do track LSC tasks in the [project](https://github.com/orgs/vitrivr/projects/4), this ticket exists.

Generally speaking, the output of this task is not **new** images, but the existing LSC images **enriched with the provided metadata**.

**Comment by ppanopticon** [comment]
Done!
