### ISSUE TITLE
Deadlock on Failed extraction

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#69]
Context: Ingesting images using an external feature extraction endpoint (clip).

On timeout from external API an exception is thrown (in this specific case from `ApiWrapper` on starting the job).
In general the pipeline deadlocks if an exception is thrown during `executeJob`.

![image](https://github.com/vitrivr/vitrivr-engine/assets/14836278/e374daea-92e3-4eae-acb5-2c89962d0df4)

**Comment by ppanopticon** [comment]
What is the status of this issue?

**Comment by ppanopticon** [comment]
Resolved based on feedback from weekly meeting.
