### ISSUE TITLE
Add local Diskresolver path parameter

### ISSUE THREAD

**Issue by net-cscience-raphael** [vitrivr/vitrivr-engine#70]
Property path for disk resolver should be able to be overwritten in the pipeline config.
Use case: debugging on minimal test set, thumbs not in original folder
Use case: need to extract thumbs into different folder based on media type.

```json
     "resolvers": {
        "disk": {
          "factory": "DiskResolver",
          "parameters": {
            "location": "D:/ptt/thumbnails"
          }
        }
      },
```
```json
    "contentFactory": "CachedContentFactory",
    "resolverName": "disk",
    "local": {
```

**Comment by ppanopticon** [comment]
What is the status of this issue?

**Comment by ppanopticon** [comment]
No longer necessary.
