### ISSUE TITLE
ApiWrapper throws exception causing extraction to halt

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-engine#73]
During extraction with the `DenseEmbedding` (model: `dino-v2-vits14`), an error occurred:

```
ERROR ApiWrapper - Job on Host <HOST> with ID: 79be39f5-5975-4723-b97e-71a8152316e2 returned no result.
```

Since the `ApiWrapper` does throw an exception in line 50, the extraction stopped. I could not find any issue with the feature exctraction server, thus more information would be helpful.

I would suggest to simply ignore those that could not be extracted and log this (possibly with the source), as the extraction should only be stopped in dire situations.

**Comment by faberf** [comment]
Thanks for bringing this to my attention! I will look into this and hopefully address it by the end of the week.
