### ISSUE TITLE
Build Improvements

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-engine#75]
Currently, the build includes JARS for all plattforms (for some of the dependencies), we should cleanup and optimise the build process to have more lean distributions.

**Comment by sauterl** [comment]
Removing myself from this issue due to time constraints. @faberf or @net-cscience-raphael , would you mind to have a look at this?

**Comment by faberf** [comment]
Hey, I am inexperienced with this sort of thing, but I would like to try tackling this. Will look into this starting tomorrow.

**Comment by sauterl** [comment]
@faberf I am not sure anymore which ones in particular. To me, one way on finding out which dependencies are OS specific (and therefore should not be included always) is a build on one OS and then manually find non-OS specific jars in the lib folder (e.g. after a `gradlew distZip`)

**Comment by sauterl** [comment]
Among others, tesseract, opencv, openblas are dependencies which have OS dependent JARs.

**Comment by ppanopticon** [comment]
@faberf I have just cleaned-up the dependencies in the [feature/3d-preview](https://github.com/vitrivr/vitrivr-engine/tree/feature/3d-preview) branch. Maybe this can act as an inspiration.

**Comment by net-cscience-raphael** [comment]
see #108
