### ISSUE TITLE
Add support for dense retrieval with instructions

### ISSUE THREAD

**Issue by faberf** [vitrivr/vitrivr-engine#76]
Some newer embedding models such as https://huggingface.co/intfloat/e5-mistral-7b-instruct require a one-sentence instruction that describes the retrieval task in addition to the content that should be embedded. This model in particular is currently implemented in the FES and accessible through the ApiWrapper. It might be useful to extend the DenseEmbedding analyser to support these models as well. To accomplish this the DenseEmbedding analyser (or its methods) needs the task instruction (e.g. 'Given a web search query, retrieve relevant passages that answer the query')  as a parameter. I would like to ask for your feedback if this should be configured as part of a query or as part of the field. My intuition is that it is a parameter of the query and thus should be passed as query context to newRetrieverForContent... Any thoughts?

**Comment by ppanopticon** [comment]
When going through the open issue, we were not quite sure what this is about. So maybe you can bring us up to speed.

**Comment by faberf** [comment]
For housekeeping, this is already implemented in feature branch #83.
