### ISSUE TITLE
Harmonise Configuration Languages

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-engine#80]
There are three (separate) configuration languages for the 

1. schema - `SchemaConfig`
2. ingestion - `IngestionConfig`
3. query - `InformationNeedDescription`

I assume, historically, they differ in approaches chosen and I suggest to harmonise them.

In particular, both, the ingestion and query languages use a named-block approach:

```json
"text-input":{"type":"TEXT","data":"my-text"}
```

while the schema configuration's blocks have a `name` property (for fields and exporters, resolvers excempt)

```json
{
"name":"averagecolor",
"factory":"AverageColor"
}
```

I would like to introduce the named-block approach in the schema configuration as well, since the other languages already use this.

Any thoughts?

**Comment by sauterl** [comment]
Removing myself from this issue due to time constraints. @faberf or @net-cscience-raphael , would you mind to have a look at this?

**Comment by faberf** [comment]
Hey, just saw this. Will work on this starting tomorrow afternoon!

**Comment by v0idness** [comment]
Following some redistribution of work, I will be taking over this issue.

**Comment by ppanopticon** [comment]
This has been adressed with #89

**Comment by ppanopticon** [comment]
Rahel and I just stumbled upon an issue: The examples have not been updated on `dev` (see `/example-configs`)

Could you please have a look @v0idness ?

**Comment by v0idness** [comment]
Looks like those examples crossed paths with the restructuring. Thank you for making me aware. I'll update them accordingly.
