### ISSUE TITLE
Cleanup Repository / Config

### ISSUE THREAD

**Issue by sauterl** [vitrivr/vitrivr-engine#81]
Recently, I removed some very old configs in the repository which were located in `config-pipelines`.

On the dev branch, there is a bit of a mess regarding example configurations:

* We have project-specific configurations located in `config/ptt`
* There are various examples as `*.json` in the root of the repo, with varying degrees of correctness (at this point in time).

I'd suggest the following:

1. Remove all project specific configurations
2. Have _one_ location for example configs
3. Those example configs should have self-explanatory names (e.g. there is a `config-lsc-metadata.json` by @faberf which has nothing to do with LSC)

Suggested order:

```
example-configs/
  |
 + schema/
    |
    - schema.json
  |
 + ingestion/
    |
    - simple-image.json
    |
    - fes-image.json
    |
    - simple-video.json
    |
    - fes-video.json
    |
    - simple-mesh.json
  |
 + retrieval/
    |
    - vectory-query.json
    |
    - text-query.json
    |
    - image-query.json
    |
    - id-query.json
    |
    - simple-boolean-query.json 
```

Any thoughts?

It might be an overkill to have these configs in the repo and simply move them to the wiki...

**Comment by net-cscience-raphael** [comment]
see d0b99f8909735546063e5e2e578d0bf4bd1cfd24
