### ISSUE TITLE
DINO & CLIP Extractors: 500 Internal Server Error

### ISSUE THREAD

**Issue by Lanceeeelot** [vitrivr/vitrivr-engine#85]
I followed the getting started and example wiki pages to setup the Vitrivr-engine and all extractors used in the example work for my videos except DINO & CLIP. I did the cottontailDB (v16.5) and FES (faberf username with all plugins) Setup via Docker.

It does not look like the amount of videos or length of individual videos matter. I attached a screenshot of the logs of the vitrivr-engine and fes console windows:

![Bildschirmfoto vom 2024-07-11 15-09-13](https://github.com/vitrivr/vitrivr-engine/assets/86054340/60b551b9-d52e-4e15-bca6-62d21e4f0a43)
![Bildschirmfoto vom 2024-07-11 15-09-52](https://github.com/vitrivr/vitrivr-engine/assets/86054340/2f19cd99-6b59-4e3e-b201-41d5b19760ed)

**Comment by sauterl** [comment]
@faberf Could  you investigate this? To me, this seems to be an issue with the FES.

**Comment by faberf** [comment]
I will have a look at this!

**Comment by faberf** [comment]
Hey @Lanceeeelot, I pushed a new image to my docker hub under the tag full-latest. Can you try if the problem goes away now? I haven't had the opportunity to test with windows yet.

**Comment by Lanceeeelot** [comment]
Thanks for the quick help. Looks like the new image fixed the Problem. I'm testing in Linux (Ubuntu 24.04) and not Windows.
