### ISSUE TITLE
Missing Implementation in FES / ImageClassification

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#96]
The retrieval side of the `org.vitrivr.engine.base.features.external.implementations.classification.ImageClassification` is currently missing. I think it would make sense to have an implementation for the first release candidate.

Basically, what we need here is an extension of a simple `AbstractRetriever`. Optionally, the retriever generates labels from an incoming image and uses them for the query.

**Comment by faberf** [comment]
> Optionally, the retriever generates labels from an incoming image and uses them for the query.
I cannot imagine when this would be useful at the moment.

#98 I think this is already fine, no?

**Comment by ppanopticon** [comment]
Closed! Thanks @faberf
